In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('D:/Dnk_project/NLP/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.shape

(5572, 2)

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [8]:
df['spam'] = df.Category.apply(lambda x: 1 if x =='spam' else 0)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
v = CountVectorizer()

In [12]:
from sklearn.model_selection import train_test_split

In [47]:
xtrain, xtest, ytrain, ytest = train_test_split(df.Message, df.spam, test_size = 0.2)

In [48]:
xtrain.shape

(4457,)

In [49]:
xtrain_cv = v.fit_transform(xtrain)

In [50]:
xtrain_cv

<4457x7702 sparse matrix of type '<class 'numpy.int64'>'
	with 59295 stored elements in Compressed Sparse Row format>

In [51]:
xtrain_cv = xtrain_cv.toarray()
xtrain_cv

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
xtrain

1810                Aight, I'll ask a few of my roommates
4368    I like dis sweater fr mango but no more my siz...
905     We're all getting worried over here, derek and...
1945    Yeah, I'll leave in a couple minutes &amp; let...
3277    Lol your right. What diet? Everyday I cheat an...
                              ...                        
3150               Sorry,  in meeting I'll call you later
3593                                    I anything lor...
2349                That seems unnecessarily affectionate
2255                              Ok. Me watching tv too.
3933                       Sos! Any amount i can get pls.
Name: Message, Length: 4457, dtype: object

In [23]:
np.where(xtrain_cv[0]!=0)

(array([ 883, 1099, 2838, 4152, 4648, 4875, 5804], dtype=int64),)

In [26]:
# Create a list of feature names (words) from the vocabulary
feature_names = v.get_feature_names_out()
feature_names

array(['00', '000', '000pes', ..., 'zouk', 'èn', '〨ud'], dtype=object)

In [32]:
xtrain._data

SingleBlockManager
Items: Index([1810, 4368,  905, 1945, 3277, 4715, 4860, 1289, 1955,  324,
       ...
       2103,  727, 2166, 4326,  336, 3150, 3593, 2349, 2255, 3933],
      dtype='int64', length=4457)
ObjectBlock: 4457 dtype: object

In [33]:
import seaborn as sns
import matplotlib.pyplot as plt

In [52]:
xtrain_cv.shape

(4457, 7702)

In [40]:
np.where(xtrain_cv[0]!=0)

(array([ 883, 1099, 2838, 4152, 4648, 4875, 5804], dtype=int64),)

In [55]:
ytrain.shape

(4457,)

In [56]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(xtrain_cv, ytrain)

MultinomialNB()

In [59]:
xtest_cv = v.transform(xtest)

In [60]:
from sklearn.metrics import classification_report
ypredict = model.predict(xtest_cv)
print(classification_report(ytest, ypredict))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       962
           1       0.97      0.93      0.95       153

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [61]:
from sklearn.pipeline import Pipeline

In [63]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())

])

In [64]:
clf.fit(xtrain, ytrain)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [65]:
ypredict1 = clf.predict(xtest)

In [66]:
print(classification_report(ytest, ypredict1))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       962
           1       0.97      0.93      0.95       153

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

